"""Stable human-readable questions for the 100-question Coverage Inventory.

The wording is adapted from the user-supplied ``DnD 2024 Character Data
Schema``.  It is a question catalog, not a claim that CharacterCheck fully
implements that schema or the 2024 rules.  Row state and authority remain the
deciding contract for whether an extracted answer may be relied upon.
"""

CATALOG_ID = "dnd-2024-character-questions-v1"

QUESTIONS = (
    "What is the character's name?",
    "What is the player's name?",
    "What is the character's Class and current Level?",
    "What is the character's Subclass?",
    "What is the character's Species?",
    "What is the character's Background?",
    "What is the character's Alignment?",
    "How many Experience Points does the character have?",
    "What is the character's Size (Small, Medium, Large)?",
    "What is the character's Age?",
    "What is the character's Hit Point Maximum?",
    "What are the character's Current Hit Points?",
    "Does the character have any Temporary Hit Points?",
    "What is the character's total pool of Hit Dice?",
    "How many Hit Dice are currently available to spend?",
    "How many Death Saving Throw successes does the character have?",
    "How many Death Saving Throw failures does the character have?",
    "What is the character's current Exhaustion level (0-6) based on 2024 rules?",
    "Does the character currently have Heroic Inspiration?",
    "What is the character's Armor Class (AC)?",
    "What is the character's Proficiency Bonus?",
    "What is the character's Initiative modifier?",
    "What is the character's Strength score?",
    "What is the character's Strength modifier?",
    "What is the character's Dexterity score?",
    "What is the character's Dexterity modifier?",
    "What is the character's Constitution score?",
    "What is the character's Constitution modifier?",
    "What is the character's Intelligence score?",
    "What is the character's Intelligence modifier?",
    "What is the character's Wisdom score?",
    "What is the character's Wisdom modifier?",
    "What is the character's Charisma score?",
    "What is the character's Charisma modifier?",
    "Is the character proficient in Strength saving throws?",
    "Is the character proficient in Dexterity saving throws?",
    "Is the character proficient in Constitution saving throws?",
    "Is the character proficient in Intelligence saving throws?",
    "Is the character proficient in Wisdom saving throws?",
    "Is the character proficient in Charisma saving throws?",
    "What is the character's base walking speed?",
    "Does the character have any other speeds (Fly, Swim, Climb)?",
    "What is the character's Passive Perception?",
    "What is the character's Passive Insight?",
    "What is the character's Passive Investigation?",
    "What is the character's Acrobatics modifier and proficiency level?",
    "What is the character's Animal Handling modifier and proficiency level?",
    "What is the character's Arcana modifier and proficiency level?",
    "What is the character's Athletics modifier and proficiency level?",
    "What is the character's Deception modifier and proficiency level?",
    "What is the character's History modifier and proficiency level?",
    "What is the character's Insight modifier and proficiency level?",
    "What is the character's Intimidation modifier and proficiency level?",
    "What is the character's Investigation modifier and proficiency level?",
    "What is the character's Medicine modifier and proficiency level?",
    "What is the character's Nature modifier and proficiency level?",
    "What is the character's Perception modifier and proficiency level?",
    "What is the character's Performance modifier and proficiency level?",
    "What is the character's Persuasion modifier and proficiency level?",
    "What is the character's Religion modifier and proficiency level?",
    "What is the character's Sleight of Hand modifier and proficiency level?",
    "What is the character's Stealth modifier and proficiency level?",
    "What is the character's Survival modifier and proficiency level?",
    "What armor categories (Light, Medium, Heavy, Shields) is the character proficient with?",
    "What weapon categories (Simple, Martial) is the character proficient with?",
    "Which specific tools is the character proficient with?",
    "What languages does the character know?",
    "What Origin Feat did the character gain from their Background?",
    "What General Feats does the character possess?",
    "Does the character possess any Epic Boons (Level 19+)?",
    "What innate traits does the character gain from their Species?",
    "What core Class Features does the character have?",
    "What features does the character gain from their Subclass?",
    "What is the character's primary class resource (for example, Rage or Focus Points) and current amount?",
    "What Weapon Masteries does the character know?",
    "Which equipped weapons have active Mastery properties?",
    "What is the name of the primary melee weapon?",
    "What is the Attack Bonus for the primary melee weapon?",
    "What is the damage dice and type for the primary melee weapon?",
    "What is the name of the primary ranged weapon?",
    "What is the Attack Bonus for the primary ranged weapon?",
    "What is the damage dice and type for the primary ranged weapon?",
    "What specific armor and shield is currently equipped?",
    "What is the character's Spellcasting Ability?",
    "What is the character's Spell Save DC?",
    "What is the character's Spell Attack Bonus?",
    "What Cantrips does the character know?",
    "What Spells does the character currently have prepared?",
    "What is the maximum number of spell slots available per spell level?",
    "How many spell slots are currently unspent per spell level?",
    "How much Copper, Silver, Electrum, Gold, and Platinum does the character have?",
    "What mundane items, tools, and adventuring gear are in the character's inventory?",
    "What is the character's total Carrying Capacity in pounds?",
    "What is the current total weight of all carried items?",
    "What magic items does the character own?",
    "Which magic items is the character currently attuned to (and what is their max attunement slots)?",
    "What is the character's height, weight, hair, skin, and eye color?",
    "What are the character's defined Personality Traits, Ideals, Bonds, and Flaws?",
    "What is the character's written backstory or character history?",
    "What allies, organizations, or Bastions (2024 DMG) is the character affiliated with?",
)

if len(QUESTIONS) != 100:
    raise RuntimeError("the Coverage Inventory question catalog must contain 100 rows")

QUESTION_BY_NUMBER = {number: question
                      for number, question in enumerate(QUESTIONS, start=1)}
